# Imagen base
FROM node:18-alpine

# Crear carpeta de la app
WORKDIR /app

# Copiar dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar código
COPY . .

# Exponer puerto
EXPOSE 3000

# Ejecutar la app
CMD ["node", "index.js"]
